# Generated by Django 3.0.8 on 2021-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.IntegerField()),
                ('username', models.CharField(max_length=250)),
                ('companyName', models.CharField(max_length=300)),
                ('applyDate', models.DateField()),
                ('responseDate', models.DateField()),
                ('jobLocation', models.CharField(max_length=150)),
                ('jobProfile', models.CharField(max_length=150)),
                ('jobType', models.CharField(choices=[('I', 'Internship'), ('J', 'Full Time')], max_length=50)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
