# Generated by Django 3.0.8 on 2021-02-14 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdata',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='serialNumber',
        ),
        migrations.AddField(
            model_name='applicationdata',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('S', 'Selected'), ('P', 'Pending')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
