# Generated by Django 3.0.8 on 2021-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationData', '0002_auto_20210214_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdata',
            name='jobType',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Full Time', 'Full Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Selected', 'Selected'), ('Pending', 'Pending')], max_length=100),
        ),
    ]
