# Generated by Django 3.0.8 on 2021-02-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationData', '0003_auto_20210226_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
