# Generated by Django 3.0.8 on 2021-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationData', '0004_auto_20210226_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdata',
            name='jobType',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Full Time', 'Full Time')], max_length=150),
        ),
    ]
