# Generated by Django 3.0.8 on 2021-02-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationData', '0005_auto_20210228_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdata',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
