# Generated by Django 3.0.8 on 2021-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationData', '0006_auto_20210228_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyID', models.IntegerField()),
                ('companyName', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Selected', 'Selected'), ('Pending', 'Pending')], max_length=100),
        ),
    ]
