# Generated by Django 3.0.8 on 2021-04-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationData', '0007_auto_20210421_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='companyDiscription',
            field=models.TextField(default='Not defined as of Now'),
            preserve_default=False,
        ),
    ]
